services:
  mysql:
    image: mysql:8.0
    container_name: digital-fit-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_fit
    ports:
      - "3307:3306"
    volumes:
      - digital_fit_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./Backend\digital-fit
    container_name: digital-fit-backend
    restart: always
    environment:
      DB_URL: jdbc:mysql://mysql:3306/digital_fit?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./Frontend\digital-fit-frontend
    container_name: digital-fit-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  digital_fit_mysql_data: