package com.example.digital_fit.model.Enums;

public enum TipoDeValoracion {
    CENTRO_PRIVADO_BASE,
    CENTRO_PRIVADO_USUARIO,

    LUGAR_PUBLICO_BASE,
    LUGAR_PUBLICO_USUARIO,

    ENTRENAMIENTO_BASE,
    ENTRENAMIENTO_USUARIO,
    HISTORIAL_ENTRENAMIENTO,
    ENTRENAMIENTO_COMUNIDAD
}
