spring.application.name=digital_fit
spring.datasource.url=jdbc:mysql://localhost:3306/digital_fit
spring.datasource.username=root
spring.datasource.password=calicanto01

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true